### ISSUE TITLE
Salesforce Data Sync

### ISSUE THREAD

**Issue by pjw6193** [revaturelabs/caliber#790]
### Issue Description
The Import Batch feature #512 is an extremely handy feature, but it is also a beautiful way to keep stale data in Caliber. To keep data up-to-the-minute, we would need to involve the Salesforce team to push events to Caliber (or a message queue), which is not feasible until their V2 release. 

As a temporary solution, Caliber should run a batch job each night at midnight to check Salesforce for updated information. Caliber will call the REST API to find all batches and associates for batches that have already started, then update its own records **if** any information has changed.

### Background/Context
Batches and trainees that have been committed to the Salesforce database are extracted from the Salesforce REST API and copied into the Caliber database. However, if trainee or batch data is updated in the Salesforce, these changes are not reflected in the Caliber. This leads to things like Dropped trainees continuing to appear in the evaluation pages.

### Value Add (feature)
Not exactly live-streaming of data, but much more up-to-date data.

**Comment by erchiggins** [comment]
Details:
Spring Task Integration: 
No new dependencies were added
Package: org.springframework.core.task
Created an application context in spring-task.xml in the “web-inf/web” folder
Declared it under context-param in the web.xml because it is a resource that is available to the whole application. 
Used @scheduled annotation and cron expressions to call function to update batch at specified time. 
Additions:
spring-tasks.xml in WEB-INF
Package: org.springframework.core.task
BatchUpdate.java (bean) 
PopulateResourceId.Java
SalesforceAuth.java (service)
New Test class: 
BatchUpdateTest.java in the unit test package 
Retrieves a batch from the Caliber database, creates a copy of it with modified details
Tests the compareBatches function which takes in two lists of batches as arguments and returns true if the batch has been modified in the Caliber database
Salesforce User creation class:
SalesforceAuth.java in the tasks package
To create a Salesforce user for a batchUpdate call setUser()
setUser() returns a boolean indicating if the Salesforce user was successfully set in the database
When the Salesforce user is no longer needed call 
clearUser() to clear the information
